apiVersion: v1
kind: Service
metadata:
  name: flyte-binary
  namespace: flyte
  annotations:
    cloud.google.com/load-balancer-type: "Internal"  # Ensures it's an internal LB
spec:
  type: LoadBalancer
  loadBalancerIP: 10.132.0.6  # Choose a private IP from your VPC
  selector:
    app.kubernetes.io/name: flyte-binary
  ports:
    - name: http
      port: 8088
      targetPort: 8088
    - name: grpc
      port: 8089
      targetPort: 8089
